server:
  port: 4001

spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    username: root
    password: root
    url: r2dbc:mysql://localhost:3307/patient_db


  cloud:
    function:
      definition: processTransferFund
    stream:
      bindings:
        processTransferFund-in-0:
          destination: transactEvent
        processTransferFund-out-0:
          destination: accountEventSuccess
        accountEventFailure-out-0:
          destination: accountEventFailure
      kafka:
        binder:
          brokers: localhost:9092
logging:
  level:
    root: info

  sql:
    init:
      mode: always