server:
  port: 4001

spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    username: root
    password: root
    url: r2dbc:mysql://localhost:3307/patient_db
#  liquibase:
#    url: jdbc:mysql://localhost:3307/patient_db
#    user: root
#    password: root
#    change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  level:
    root: info

  sql:
    init:
      mode: always